version: "3"

services:
  wikidb:
    image: bitnami/postgresql:16.3.0
    container_name: wikijs-bitnami-postgres
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - ./data-new:/bitnami/postgresql
    restart: always
    networks:
      - wikigit

  wiki:
    image: jionggyu/starchart:0.9
    depends_on:
      - wikidb
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./favicons:/wiki/assets/favicons
      - ./favicons/favicon.ico:/wiki/assets/favicon.ico
    networks:
      - wikigit
    restart: unless-stopped
    ports:
      - "3000:3000"

  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      GITEA__database__DB_TYPE: ${GT_DB_TYPE}
      GITEA__database__HOST: ${GT_DB_HOST}
      GITEA__database__NAME: ${GT_DB_NAME}
      GITEA__database__USER: ${GT_DB_USER}
      GITEA__database__PASSWD: ${GT_DB_PASSWD}
    restart: always
    networks:
      - gitea
      - wikigit
    volumes:
      - ./!gitea-service/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "222:22" # SSH
    depends_on:
      - gitdb

  gitdb:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${GT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${GT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${GT_POSTGRES_DB}
    networks:
      - gitea
      - wikigit
    volumes:
      - ./!gitea-service/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # gitadminer:
  #   image: adminer
  #   container_name: gitadminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - gitea
  #     - wikigit

volumes:
  db-data:
  wikidb_data:

networks:
  gitea:
    external: false
  wikigit:
    external: true
