version: "3"

services:

  wikidb:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    networks:
      - wikigit
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
      

  wiki:
    image: jionggyu/starchart:0.9
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - wikigit
    restart: unless-stopped
    ports:
      - "3000:3000"

  # wikiadminer:
  #   image: adminer
  #   container_name: wikiadminer
  #   restart: always
  #   ports:
  #     - "8081:8080"  # Changed port mapping to 8081
  #   networks:
  #     - wikigit

volumes:
  db-data:

networks:
  wikigit:
    external: true
