name: Telegram Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Notify Telegram Channel
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Wiki.js **2.5.284** has been released!

            See [release notes](https://github.com/requarks/wiki/releases) for details.
